services:
  db:
    image: postgres:16.2-alpine3.19
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - .env
    networks:
      - main
      - elastic
  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
    env_file:
      - .env
    networks:
      - elastic
  mqtt:
    image: emqx/nanomq:0.21.8
    ports:
      - "1883:1883"
    expose:
      - "1883"
    networks:
      - main

networks:
  elastic:
    driver: bridge
  main:
    driver: bridge
